### ISSUE TITLE
Popper is not always first, hides behind other element

### ISSUE THREAD

**Issue by frikkfossan** [MrFrankel/ngx-popper#10]
Hello.
My implementation of ngx-popper doesn't always put the popper as the front html element.

![image](https://user-images.githubusercontent.com/31690628/30104653-89b20b1e-92f6-11e7-81be-756daf1bff61.png)

My markup:
`<a 
    *ngIf="fieldValue.field.description?.length > 0" 
    [popper]="fieldValue.field.description" 
    [popperTrigger]="'hover'"
    [popperPlacement]="'auto-top'"	
    href="javascript:void(0)" class="tooltip-icon text-left" >
    <sup>
        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
    </sup>
</a>`

I have a custom css hook for the container element aswell. Maybe this is causing the issue?

`.ngxp__container {
    text-align: left;
    opacity: 1 !important;
    background-color: #656d79;
    text-align: left;
    padding: 15px !important;
    max-width: 300px;
    font-size: 12px;
    line-height: 20px;
    border-radius: 5px !important;
    color: white;
    border: 1px solid #656d79 !important;
    border-bottom: 3px solid #434a54 !important;
  }`

How can I fix this?

**Comment by MrFrankel** [comment]
Have you trying giving the container position relative and a higher z-index?

**Comment by frikkfossan** [comment]
That worked great!
added these styles:
.ngxp__container {
    ...
    position: relative;
    z-index: 999;
}

z-index = 999 to be sure that 99% of all times it should render on top of all other elements.

**Comment by lincolnthree** [comment]
This is actually something I'm struggling with. Relative position breaks the page layout (causes popper to be rendered inline) and the z-index seems to have no effect (even with !important)

**Comment by frikkf** [comment]
Even though the z-index on the popper element has the highest value?

**Comment by MrFrankel** [comment]
@lincolnthree z-index applies to all positioned element i.e.(absolute, relative, fixed).
ngx__container is absolute by default so you can leave it at that.

You may be encountering a situation where the container element has `overflow: hidden` applied to it.

If you want to create a demo repo I can maybe help more specifically.

**Comment by lincolnthree** [comment]
So it turns out that you're right. The popper is hidden by the overflow element; however, I resolved the issue by placing the `<popper-content>` in a wider scoped tag on the page. E.g. In the `<body>` tag directly, rather than inline with the element being popped. This allowed the library to position and display the popper correctly.

**Comment by jandresampaio** [comment]
@lincolnthree, I've ran into this same problem, but can't seem to understand your solution...
We have different tooltip templates so would the component find out about the template if the template if not the component html?

Thank you.

**Comment by MrFrankel** [comment]
@jandresampaio not sure what your issue is but since this issue was open we now have `[popperPositionFixed]="true"`

settings this will cause the popper to be above other elements.

**Comment by jandresampaio** [comment]
@MrFrankel issue is tooltip getting behind other elements...
Still, using this setting, some parts of the tooltip still get hidden below other elements. Only appying a big z-index on the popper tooltip style tooltip is above all other elements. 
Using the following: 
`        NgxPopperModule.forRoot({
            placement: 'auto',
            trigger: 'hover',
            positionFixed: true,
            styles: { "background-color": "black", "color": "white"}
        }),`

We get the effect on this cards list:

![image](https://user-images.githubusercontent.com/13848625/43907804-40d3694a-9bee-11e8-9def-2ad601ab2841.png)

**Comment by MrFrankel** [comment]
does one of the popper parent's have a transform property set to it? if so that will change the view stack for the 'fixed' element.

Also, make sure that __ngx__container  has z-index set to it.

If that dosn't help I have a task to add a new property called popperPinToBody which will place the popper on the body and thus be above all other nested elements.

Should be able to push it in the next couple of days.

**Comment by jandresampaio** [comment]
That's a very nice feature, thank you....
Will that just use one popper DOM element that renders the different tooltips configured inside each component ? Because now, when using *ngFor, a new element is added to the dom which causes some performance issues.

**Comment by MrFrankel** [comment]
Well, since there may be few poppers open at the same time.
The idea is to remove the poppers when they are hidden and show them when they are shown.

**Comment by MrFrankel** [comment]
@jandresampaio try version 5.0.0-beta4, with :
`[popperAppendToBody]="true"`

**Comment by jandresampaio** [comment]
Thank you @MrFrankel 
Can I set this as global setting, in bootstrap module ? Tried but the setting doesn't seem to exist yet. This would be good to have for testing all system areas.

**Comment by MrFrankel** [comment]
global listeners are not prefixes with popper,

try with appendToBody

**Comment by jandresampaio** [comment]
Yeah...code editor was giving me an error on that but finally after restarting appendToBody was no longer an issue.

It seems that this settings causes performance issues when we have a lot of poppers around. I'll try to investigate this in more detail.

**Comment by MrFrankel** [comment]
@jandresampaio lets move this discussion to #72

**Comment by gtaylor44** [comment]
createPopper(reference, popper, {
  strategy: 'fixed',
});

Default position is "absolute". This resolved the issue for me.
