### ISSUE TITLE
Inconvenient working experience with the option `{preventOverflow:{enabled:false}}` for `popperModifiers` 

### ISSUE THREAD

**Issue by dmytro-krekota** [MrFrankel/ngx-popper#105]
Hi @MrFrankel, I use your library and setting the option `[popperModifiers]="{preventOverflow:{enabled:false}}"` in HTML is too strange and not obvious to me. I discovered how to set it only after browsing source files. So, my suggestion is to add an alias, for example `[popperPreventOverflow]="false"` or `[popperPreventOverflowEnabled]="false"`. What do you think about it? If you ok with it, I can create a pull request with the feature.

**Comment by MrFrankel** [comment]
there are many modifiers that popper.js exposes, I don't wish to add in Input for each of them as the directive already holds many Input.
However I agree that preventoverflow is a common one and it would be a good idea to add an Input for it,
I would prefer popperPreventOverflowEnabled.

A PR would be gr8, just keep in mind that preventOverflow: {enabled: false} should be paired with hide: {enabled: false}
