### ISSUE TITLE
popperTimeoutAfterShow 

### ISSUE THREAD

**Issue by jaipresto** [MrFrankel/ngx-popper#109]

**Comment by jaipresto** [comment]
[...Sorry I hit enter by accident]. Issue is simply that the popperTimeoutAfterShow doesn't work if the initial show is done programmatically. For example:

```html
[popper]="resumeMsg"
[popperTrigger]="'none'"
[popperApplyClass]="'classic-tooltip, dark-tint'"
[popperBoundaries]="'ion-content'"
[popperPreventOverflow]="true"
[popperTimeoutAfterShow]="'15000'"
[popperPlacement]="'top'"
```
shown by calling

``` typescript
resumeMsg.show()
```

does not hide after 15 seconds. I've tried: passing the number in quotes, different times, and mixing various other options - but nothing works. Not sure if this is intentional, or something not thought about. It's easily solved of course with a simple setTimeout and .hide(), but it would be better built into the directive.

**Comment by MrFrankel** [comment]
@jaipresto when working with the API you override the directive ability to know when to hide the popper. since you are showing the popper programatically I suggest you hide it programatically too.

**Comment by jaipresto** [comment]
@MrFrankel As I thought. Thanks for the response though :)
