### ISSUE TITLE
Poppers used in *ngFor loops seem to attach only to last rendered item in loop

### ISSUE THREAD

**Issue by lincolnthree** [MrFrankel/ngx-popper#11]
Hey, it's me again :)

So apparently I'm experiencing an odd behavior. When using poppers in an `*ngFor` loop, no matter which item (with the popperTrigger attribute) you actually trigger, the popper will render on the last element of the list.

```
<ion-item *ngFor="let reg of registrations; let i = index;" class="reg">
   <a target="_blank" href="..." ion-button small icon-only
                    [popper]="viewPublic" popperTrigger="hover" popperPlacement="bottom">
                    <ion-icon name="link"></ion-icon>
                  </a>
</ion-item>
```
```
<popper-content #viewPublic><p>
  View public profile
</p></popper-content>
```

Thoughts?

**Comment by MrFrankel** [comment]
@lincolnthree i have just pushed a fixed for this on version 1.2.0
try it out and let me know.

regardless, if the content of the popper is just text you can either use popper as a text input, i.e:
```<a target="_blank" href="..." ion-button small icon-only
                    popper="View Public Profile" popperTrigger="hover" popperPlacement="bottom">```

or binding reference

```<a target="_blank" href="..." ion-button small icon-only
                    [popper]="someItemText" popperTrigger="hover" popperPlacement="bottom">```

**Comment by lincolnthree** [comment]
Confirmed this is fixed! I tried the plain input, but then I get into the issue of the popper being hidden by elements with "overflow: hidden;" - Putting the <popper-content> tag closer to the root level helps overcome that issue. (Would be nice if it didn't have to work that way though!)

Thank you for the quick fix!

**Comment by MrFrankel** [comment]
I am restricted by the implementation of popper.js, ill open a discussion with the author @FezVrasta if he can add support for overflow: hidden in popper.js
