### ISSUE TITLE
popper.js peerDependency is locked to a specific version

### ISSUE THREAD

**Issue by Necroskillz** [MrFrankel/ngx-popper#110]
Not sure if this is intended, but in on of 6.x releases you set peerDependency of popper.js to `1.14.3`. I had to downgrade it. If there is not a specific reason for it, could you set it to a range like `^1.14.3` or at least `~1.14.3`.

If popper.js correctly uses semantic versioning, this will allow us to use latest fixes without changes required in this library.

**Comment by MrFrankel** [comment]
@Necroskillz ill fix it next release, probably in the next couple of days

**Comment by vinayakpatil** [comment]
+1

**Comment by MrFrankel** [comment]
fixed in 6.0.7, please verify

**Comment by vinayakpatil** [comment]
Thanks @MrFrankel , works as expected now.
