### ISSUE TITLE
Popper with popperTimeoutAfterShow remains open

### ISSUE THREAD

**Issue by sirrocco** [MrFrankel/ngx-popper#112]
Hi,

I'm getting a reference to the popper directive using ViewChild and on it I'm calling the `show` method. If I call it again within the timeoutAfterShow window, then the timeout gets cleared and the popper remains open.

Is it not ok to use the directive directly? Are you open to changing this behavior?

Thanks.

**Comment by MrFrankel** [comment]
why don't you get a reference to the popper-content element and call show/hide on it?

**Comment by sirrocco** [comment]
If I use popper content it ignores the `timeoutAfterShow` property

**Comment by MrFrankel** [comment]
If you are using the popper programatically then you should manage the timeout yourself
trying to support a mix of programmatic and configuration can get very complicated.

**Comment by sirrocco** [comment]
The only thing is that it's strange that the behavior is different when opened programatically vs user action. Why is the timeout ignored in this case?

Thanks

**Comment by MrFrankel** [comment]
when you use it via a user action, a second click on an element will trigger a hide event which cleared the isShown flag.

Programatically you can trigger hide right before triggering show again, which will clear the flag. 

Cant guarantee this scenario as I said, I don't support this logic programatically
