### ISSUE TITLE
How to configure with SystemJS?

### ISSUE THREAD

**Issue by kgrvr** [MrFrankel/ngx-popper#12]
Getting this error when importing using SystemJS:
![image](https://user-images.githubusercontent.com/11766028/30729403-de796fce-9f7c-11e7-8f5f-188fe629d0b7.png)

This is my SystemJS:
```javascript
(function (global) {
    System.config({
        paths: {
            'npm:': 'libs/'
        },
        map: {
            ....
            'ngx-popper': 'npm:ngx-popper'
        },
        packages: {
            ....
            'ngx-popper': {
                main: 'index.js',
                defaultExtension: 'js'
            }
        }
    });
})(this);
```

I've also used Gulp to copy index.js, popper.js, popper-content.js, popper.model., and popper.module.js from node_modules directory to my project's libs folder.

My Gulp file:
```javascript
gulp.task('restore:ngx-popper', function () {
    gulp.src([
        'node_modules/ngx-popper/src/*.js'
    ]).pipe(gulp.dest(libs + 'ngx-popper'));
});
```

What's wrong I'm doing?

**Comment by kgrvr** [comment]
Okay, I solved it by importing Popper.JS too in the similar way as above.
But now I'm getting another error while importing NgxPopperModule in my module file.

![image](https://user-images.githubusercontent.com/11766028/30733485-c0579c06-9f94-11e7-89af-ba72aa0251c0.png)

```javascript
import { NgModule } from '@angular/core';
import { NgxPopperModule } from 'ngx-popper';

@NgModule({
    imports: [
...
        NgxPopperModule
    ],
    declarations: [
...
    ],
    exports: [
...
        NgxPopperModule
    ],
    providers: [
...
    ]
})

export class CoreModule { }
```

**Comment by MrFrankel** [comment]
I have no experience working with SystemJs, from the error it seems the NgxPopperModule is not getting imported properly hence the "undefined".

if you can supply a demo page I can try looking into it.

**Comment by kgrvr** [comment]
Hey, Thanks for the reply. 
See the issue was that index.ts file was not importing popper.module file and popper.js file. So to solve this I needed to explicitly tell SystemJS to load these two files, which usually does not happen.

```javascript
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'libs/'
        },
        // map tells the System loader where to look for things
        map: {
            ... ,
            'ngx-popper': 'npm:ngx-popper',
            'popper.js': 'npm:ngx-popper',
            'popper.module': 'npm:ngx-popper',
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            ... ,
            'ngx-popper': {
                main: 'index.js',
                defaultExtension: 'js'
            },
            'popper.js': {
                main: 'popper.js',
                defaultExtension: 'js'
            },
            'popper.module': {
                main: './popper.module.js',
                defaultExtension: 'js'
            }
        }
    });
})(this);
```

Its better if you just figure it out how to do it directly, i.e. without the users of library to do it explicitly.
This solved this issue.. Thanks. 

I'm having some other issue too.. I'm trying to solve it.. Will as for your help if needed. :)

**Comment by MrFrankel** [comment]
Let me know if you need anything else,
Ill add this to the docs.

Thanks1
