### ISSUE TITLE
NullInjectorError: StaticInjectorError(AppModule)[popperDefaults]

### ISSUE THREAD

**Issue by leonardofmed** [MrFrankel/ngx-popper#122]
Hi, I'm having some troubles adding this library in my project. I already used this library before without problems, but now, implementing this the same way as before give me this error:

> ERROR Error: "Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[popperDefaults]: 
>   StaticInjectorError(Platform: core)[popperDefaults]: 
>     NullInjectorError: No provider for popperDefaults!

I checked the documentation, everything looks exactly the same. I imported the module in various ways and in different locations and still receive this error no matter what I try. 

Using Ionic v4 and ngx-popper v7.0.0

Tried to import in app.modules.ts:
```
import {NgxPopperModule} from 'ngx-popper';
...
@NgModule({k
    ...
    imports: [
        NgxPopperModule
    ]
    ...
})
```
And tried to import in the page I'm using, but got the same results.

**Comment by k10der** [comment]
Hey, @leonardofmed. I ran into the same issue today. Adding `NgxPopperModule.forRoot({})` to the root app module import list seemed to resolve the problem.

**Comment by leonardofmed** [comment]
This really fixed the issue! Can you explain why I have to do this way? Also, why the default way is working in other projects I have?

**Comment by k10der** [comment]
Hey, @leonardofmed. I'm not 100% sure about the cause of this issue now.

But if we look at the code and check `popper-directive.ts` we'll see that it depend on injectable with string injection token (which I don't think is allowed at the moment - maybe it was OK in the past).

![image](https://user-images.githubusercontent.com/6381515/64925322-61402b00-d7f7-11e9-9b39-a105a0da10df.png)

This injection token doesn't exist anywhere in the app, so Angular throws an error. The `forRoot` method of the module class contains the required provider.
![image](https://user-images.githubusercontent.com/6381515/64925331-8df44280-d7f7-11e9-8722-8e12745268f9.png)

My guess here is that previous version of Angular (and Ionic) were less strict for such stuff, so using this module as a dependency (without calling `forRoot`) didn't cause an error in injection token processing. And I believe adding `@Optional()`(https://angular.io/api/core/Optional) to the `popperDefaults` injection logic in `PopperController` constructor could resolve the issue.

**Comment by wmehanna** [comment]
> Hey, @leonardofmed. I ran into the same issue today. Adding `NgxPopperModule.forRoot({})` to the root app module provider list seemed to resolve the problem.

This should be in the doc. thanks

**Comment by odysseasdiamadis** [comment]
Today I faced this problem again, and the solution provided by @k10der didn't work.
When I tried to add `NgxPopperModule.forRoot({})` I got the following error

`Type 'ModuleWithProviders<NgxPopperModule>' is not assignable to type 'Provider'.
  Type 'ModuleWithProviders<NgxPopperModule>' is missing the following properties from type 'any[]': length, pop, push, concat, and 26 more`.

I'm using Angular 9 and ngx-popper v7.0.0

Does anyone faced the same and managed to solve?

**Comment by k10der** [comment]
Hey, @mantador. It looks like my initial message was not quite correct, as I mentioned "root app module **provider list**", which should have been "root app module **import list**". The error you're sharing here is probably related to my mistake.

So, **instead of**
```typescript
providers: [
  ...
  NgxPopperModule.forRoot({}),
  ...
],
```
it **should** be
```typescript
imports: [
  ...
  NgxPopperModule.forRoot({}),
  ...
],
```

**Comment by odysseasdiamadis** [comment]
I admit, I copy-pasted without thinking. My fault! Thank you!
