### ISSUE TITLE
One popper for multiple targets

### ISSUE THREAD

**Issue by sirrocco** [MrFrankel/ngx-popper#123]
Hi,

Having many poppers on an already heavy page can cause performance problems. I was looking into having one popper that would be placed on the body and then programmatically open it and giving it the reference element and the content.

As far as I can see there's no way to do this with the current implementation and I should use the Popper.js library directly.

Would you say that's correct or did I miss something?

Thank you.

**Comment by mpicciollicmq** [comment]
Did you try with popperTarget attribute ?
