### ISSUE TITLE
Consider renaming popper.ts file

### ISSUE THREAD

**Issue by kgrvr** [MrFrankel/ngx-popper#14]
See I inspected your code, and found out that 
https://github.com/MrFrankel/ngx-popper/blob/860fad0b2f35725ad8b208f2e168ddde8ab1960d/src/popper-content.ts#L217
this line here is creating problem with your own popper.js (of your own library) file because 
https://github.com/MrFrankel/ngx-popper/blob/860fad0b2f35725ad8b208f2e168ddde8ab1960d/src/popper-content.ts#L9
you imported it from popper.js (Of official popper library).

This is happening because the browser is taking your own popper.js file and tries to initialize it with it's constructor and not of official popper library constructor.

Getting this error:
![image](https://user-images.githubusercontent.com/11766028/30782119-4865673a-a149-11e7-89db-9161b7ea05c3.png)

As I said above, popper directive takes 2 parameters and official popper.js takes 3 parameters and it's conflicting because you are importing it with same name. 

Hope you understood the problem.

**Comment by MrFrankel** [comment]
I see, 
since i'm using TS as the module loader it has no problem having to identical names as they are mapped to different namespaces.

Guess your saying its not the case for SystemJS.

I guess I can change the name, but Ill need to see about backwards compatibility.

Do you have a workaround for this for now?

**Comment by kgrvr** [comment]
I'm trying some other solutions..
But I can wait till you rename the file.

**Comment by MrFrankel** [comment]
It will probably take me a couple of days, as I need to verify its not a breaking change.

**Comment by kgrvr** [comment]
That's fine.. but I don't think it will break anything.
You'll just need to change the reference path of the file in three file namely: popper.module.ts, popper-content.ts and index.ts.
Rest can work as it's working.

**Comment by MrFrankel** [comment]
cool, thanks for the research!

**Comment by MrFrankel** [comment]
Fixed!
