### ISSUE TITLE
Error: Can't bind to 'popperShowOnstart' since it isn't a known property of 'div'.

### ISSUE THREAD

**Issue by jplew** [MrFrankel/ngx-popper#15]
Hi I got the following error when trying out the demo:

```
Uncaught Error: Template parse errors:
Can't bind to 'popperShowOnstart' since it isn't a known property of 'div'. ("
```

The problem is that there is a typo in the documentation:

    [popperShowOnstart]="true"

Should be:

    [popperShowOnStart]="true"

:)

**Comment by MrFrankel** [comment]
Fixed,
Thanks!

**Comment by jplew** [comment]
Thank you! Great package, easy to install and use
