### ISSUE TITLE
The tooltip can't be closed on iPhone

### ISSUE THREAD

**Issue by JorgeLoaiza12** [MrFrankel/ngx-popper#18]
While the tooltip works fine on Android devices and Chrome's mobile simulator, when seen on an iPhone, the tooltip won't close unless the page is refreshed or another tooltip is selected.

`<button class="btn-icon"
                       [popper]="popperContent"
                       [popperTrigger]="'hover'"
                       [popperPlacement]="'left'">
Open Tooltip!
</button>
                    <popper-content class="" #popperContent>
                      Text tooltip!
                    </popper-content>`

**Comment by MrFrankel** [comment]
@JorgeLoaiza12  Thanks for bringing this up, Ill take a look into it later today.

**Comment by JorgeLoaiza12** [comment]
I use it with 'Click' and it does not work either.

Create a directive and this was solved:
` ngOnInit() {
    if ('ontouchstart' in document.documentElement) {
      jQuery('body').children().on('mouseover', null, function(){});
    }
  }

  ngOnDestroy() {
    if ('ontouchstart' in document.documentElement) {
      jQuery('body').children().off('mouseover', null, function(){});
    }
  }`

**Comment by MrFrankel** [comment]
OK, seems like I just need to add an event for ontouchstart ontouchend,
Ill add it to the coming release.

**Comment by MrFrankel** [comment]
@JorgeLoaiza12 I have released a new version 1.5.11, can you please check if its fixed?

**Comment by MrFrankel** [comment]
@JorgeLoaiza12 have you had a chance to see if this is fixed?

**Comment by MrFrankel** [comment]
closing since no response
