### ISSUE TITLE
Directive [popperTimeout] does not change behavior

### ISSUE THREAD

**Issue by FloppyNotFound** [MrFrankel/ngx-popper#20]
I want to tell the popup to close after a specified amount of time, not immediately.
So I set [popperTimeout]="500" (for example) to my popper-HTML element.
The directive to control this seems to be [popperTimeout], but it doesn't matter what value I set, it doesn't change the behavior.

I guess the error lies in popper-directive.ts (https://github.com/MrFrankel/ngx-popper/blob/master/src/popper-directive.ts), Line 127.
Don't pass "0" as parameter, but the set timeout value, if available, or 0 as default.

**Comment by MrFrankel** [comment]
@FloppyNotFound The timout seems to work fine for me,
Can you please send all the parameters you are using?

**Comment by MrFrankel** [comment]
@FloppyNotFound Come to think of it, hideDelay currently only works with showOnStart.
Do you think it should also be supported on all show triggers, i.e click, hover ?

**Comment by FloppyNotFound** [comment]
@MrFrankel My customer complained that the Popup disappears too quickly, so that sometimes when he moves his mouse into the overlay, it disappears before the mouse arrow is even there (there's a link within the overlay, so he has to do that).

In order to resolve this issue I tried to increase the hide delay onHover, but setting the directive popperTimeout had no effect, so I started investigating.

//TLDR: Yes, a support at least for hover, would be great :) I think my commit should fix this issue already, what do you think?

**Comment by MrFrankel** [comment]
I see two use cases for timeout here.
One is a buffer after a hide event is triggered(mouseout, click, outsideClick)
Second is after show, always hide after a certain time passes.

So I think ill add hideTimout and hideAfterShow params, what do you think @FloppyNotFound ?

**Comment by FloppyNotFound** [comment]
Sounds great to me, thanks for the quick response! Could you please add those two too to the documentation? I had troubles finding out what hideTimeout actually does, I couldn't find it documented and had to look into the code.

**Comment by MrFrankel** [comment]
Currently hideTimeout only applies when used with showOnStart.

Ill add these params later today and add them do the documentation with a new version, if you can wait till then.

Thanks

**Comment by FloppyNotFound** [comment]
@MrFrankel Sure, thanks again!

**Comment by MrFrankel** [comment]
Just released version 1.6.0. you can now set:
popperTimeoutAfterShow, which will always hide the popper-content after the specific time after its shown.
popperTimeout, which will hide the popper at a delay when a hide event is triggered.
popperCloseOnClickOutside, default to true, in case you dont want the popper to close on a click outside

Let me know if this suites your use case.

Also, stars are appreciated 👍

**Comment by FloppyNotFound** [comment]
Hi,
thanks for the update, I will test it immediately.
I can't find popperTimeoutAfterShow and popperCloseOnClickOutside in the documentation yet, have you added them there? It would be a shame if you added them to the code and people don't know they can use them :)

**Comment by MrFrankel** [comment]
Yea, I will add them once I get the all clear from you. once I expose something I cant take it back :)

**Comment by FloppyNotFound** [comment]
Hey again, tested it (for my scenario) and it works like a charm.
Thanks again for the quick response, I will close the issue now.
