### ISSUE TITLE
Improve website

### ISSUE THREAD

**Issue by lazarljubenovic** [MrFrankel/ngx-popper#22]
The current [website](https://mrfrankel.github.io/ngx-popper/) is a nice showcase of capabilities, but it's missing couple of things (from top of my head):

- There is no link to GH repo.
- There is no code example for the effects described in demos.
- Text and images are swapped (mirrored) from the original site which is fine, but this makes third demo wrong: the popover is never on the _left_, not on the _right_.
- Would be nice to have a separate section on docs, too.

**Comment by MrFrankel** [comment]
All valid points, I will take them into account when creating a new example site.

Thanks!

**Comment by PascalHonegger** [comment]
I just wanted to mention that the current page doesn't load in firefox (57) or internet explorer (11), which leaves me as a developer concerned about browser support of the library, even though ngx-popper works flawlessly in both browsers.

**Comment by MrFrankel** [comment]
@PascalHonegger I can confirm the library is compatible with all evergreen browsers and ie10+.
The example page is indeed outdated, i'm working on it and hope to have a shiny new one out soon enough.

Thanks for brining this up!.

**Comment by MrFrankel** [comment]
@PascalHonegger the current example is fixed on FF, working on IE.
