### ISSUE TITLE
Overriding defaults should be done via DI

### ISSUE THREAD

**Issue by lazarljubenovic** [MrFrankel/ngx-popper#23]
The docs state to manually change static properties, and suggests to do it as soon as possible, even before Angular has bootstrapped.

The idiomatic way to do this in Angular is using ID with a static method on the Angular Module called `.forRoot`, and, if needed, a `.forChild`, which accept configuration object. This also allows for multiple configurations in the app based on where the popper is used, it's good for testing, etc.

**Comment by MrFrankel** [comment]
Hey, yes, this has also been on my list of enhancements, now that the package has some production users ill get to it.

I might leave the old method in place for a while as deprecated for backwards compatibility.

**Comment by MrFrankel** [comment]
Added in 1.8.3
