### ISSUE TITLE
A huge CSS file in the examples

### ISSUE THREAD

**Issue by lazarljubenovic** [MrFrankel/ngx-popper#24]
The [CSS file used for examples](https://github.com/MrFrankel/ngx-popper/blob/master/example/app/app.component.css) has a huge chunk (6k+ LOC?) of unused styles. It contains a ton of classes which are not present in the document at all so I'm assuming they are a mistake.

**Comment by MrFrankel** [comment]
@lazarljubenovic Yes, they are just copied over from the original site, I have a plan to recreate the whole example page from scratch, for now ill make sure its not part of the npm package.

Thanks for bringing it up!

**Comment by MrFrankel** [comment]
removed unused css
