### ISSUE TITLE
ngx-popper doesn't work well with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by dzNavitski** [MrFrankel/ngx-popper#25]
Using `ngx-popper` inside component with `ChangeDetectionStrategy.OnPush` affects `ngx-popper` behavior (incorrect positioning, unexpected behavior on triggers).
To reproduced the issue add `ChangeDetectionStrategy.OnPush` to the example component.

**Comment by MrFrankel** [comment]
Thanks for bringing this up,
I can reproduce the issue, ill try and get a fix out by tomorrow.

**Comment by MrFrankel** [comment]
@dzNavitski,  So, the issue is that the show and hide are wrapped in setTimouts,
In cases where `ChangeDetectionStrategy.OnPush` is declared, these do not trigger a change detection.
This has been fixed in 1.8.6, if you can confirm so I can close the bug.

Also, a start would be much appreciated :

**Comment by dzNavitski** [comment]
@MrFrankel it works great. Thanks a lot
