### ISSUE TITLE
Tooltip isn't shown unless you explicitly declare a popperTrigger in the template

### ISSUE THREAD

**Issue by PascalHonegger** [MrFrankel/ngx-popper#26]
# Situation
We want to use this library as our main tooltip library, but don't want to state `popperTrigger="hover"` every time, when `popper="my tooltip text"` would suffice. We expected the popper to show when we don't explicitly declare a popperTrigger, as the documentation states that there are configurable default values.
# Problem
Sadly, the default value doesn't work and the tooltip is only shown when explicitly declaring a popperTrigger. Ignoring the setting (`NgxPopperModule.forRoot()`) or providing a value (`NgxPopperModule.forRoot({ trigger: 'hover' })`) makes no difference (same for all other triggers, not just hover).
# Example
To ensure it has nothing to do with the rest of our project I created a [stackblitz](https://stackblitz.com/edit/angular-brj7w1), where I could easily reproduce this issue.

**Comment by MrFrankel** [comment]
@PascalHonegger Checking...

**Comment by PascalHonegger** [comment]
@MrFrankel thank you a lot for the quick response, the issue seems to be resolved. We‘ve had some terrible experiences with other open source project so it‘s refreshing to get an issue fixed and published within hours, I‘ll gladly give you a star.
