### ISSUE TITLE
Can't override 'placement' default value

### ISSUE THREAD

**Issue by slack4u** [MrFrankel/ngx-popper#28]
I have overridden `placement` default value, but it doesn't change the behavior. It seems that it is still `'auto'`.

code sample: 
```
NgxPopperModule.forRoot({ placement: 'bottom-start' }),
```

**Comment by MrFrankel** [comment]
@slack4u fixed in 1.9.6.

Good catch, thanks!

**Comment by MrFrankel** [comment]
@slack4u can we close this?

**Comment by slack4u** [comment]
@MrFrankel It works perfectly! Thanks for the quick response.
