### ISSUE TITLE
Issues when using ng build --prod

### ISSUE THREAD

**Issue by asfo** [MrFrankel/ngx-popper#3]
I'm having an issue when I use the command `ng build --prod` as seen in this image

![Error](http://i.imgur.com/SMX87oR.png)

I know the error is because the `private` property in `popper-content.ts`. Changing it to `public` works as intended. I don't know if this is the best way to fix it but does the job.

**Comment by MrFrankel** [comment]
@asfo why are you running ng build for? if you want to release a version you should run.
node_modules/.bin/ngc -p tsconfig-aot.json
&
node_modules/.bin/ngc -p tsconfig.esm.json

**Comment by asfo** [comment]
I'm doing some tests for a Service Worker and I need to build it.

**Comment by MrFrankel** [comment]
Fixed in 1.0.1, thanks for bringing this up!

And if you could punch in a star for the repo that would be great 👍

**Comment by asfo** [comment]
Amazing, thanks! :)
