### ISSUE TITLE
Click inside popper does not close popper

### ISSUE THREAD

**Issue by robertjorg** [MrFrankel/ngx-popper#30]
This is a great tool for making sure my popups go in the correct place. I am having a problem when I try to click inside of the popper-content. 

If I click on the element that opens the popper-content or anywhere around (when popperHideOnClickOutside=true) the popper-content is hidden. However, if I click inside of the popper-content is not hidden. 

Am I missing something in the code? I used all the defaults if it is not changed below

```
<div> 
               <div [popper]="descriptions" [popperShowOnStart]="false" [popperTrigger]="'click'" [popperPlacement]="'right'" [popperDisableStyle]="true"
                  [popperHideOnClickOutside]="false">
                  <div class="severity-help">
                    <img [src]="questionPath" #severityToolTip alt="" class="clickable">
                  </div>
                </div>

                <popper-content class="top-class" #descriptions>
                    <app-adverse-descriptions>
                    </app-adverse-descriptions>
                  </popper-content>
<div>
```

**Comment by MrFrankel** [comment]
@robertjorg Hey,

You can close the popper-content on click inside programmatically like so.

```
    <popper-content class="top-class" #descriptions (click)="descriptions.hide()">
                    <app-adverse-descriptions>
                    </app-adverse-descriptions>
                  </popper-content>
```

**Comment by robertjorg** [comment]
Thanks, that fixed what I needed. I should have noticed that the tool is hiding and unhiding the element. The tool is great, and thanks again.

**Comment by MrFrankel** [comment]
@robertjorg hope it serves you well.

p.s. stars are welcome :)
