### ISSUE TITLE
popover content background color set and hiding

### ISSUE THREAD

**Issue by vvavdiya** [MrFrankel/ngx-popper#32]
I have shown popover on mouse over. popover displays in transparent backgound and some partion of popover content is hiding behind other HTML. How to set the background color and zIndex of popover content?
<img width="477" alt="screen shot 2018-02-26 at 6 03 10 pm" src="https://user-images.githubusercontent.com/4570688/36670789-5b8b749e-1b1f-11e8-9ff8-e25f35725801.png">

**Comment by MrFrankel** [comment]
you can set the . ngxp__container class background property.
```
. ngxp__container{
  background: white;
  z-index: 10000;
}
```

if you can supply a demo of the issue I could help more specifically

**Comment by vvavdiya** [comment]
I am using ngx-popper in one of my angular components. I tried to add above mention class in the mycomponent.component.scss file. but the style is not overriding. How to override the ngxp__container style?

**Comment by MrFrankel** [comment]
@vvavdiya since Angular enables css encapsulation by default, the style added to your .scss file will not propagate to nested component list the popper-content.

You should either define the css in a global .scss file or use in your component 
`encapsulation : Viewencapsulation.none`

**Comment by vvavdiya** [comment]
Thanks to Frankel for help.
I added in global .scss file and it works.

**Comment by MrFrankel** [comment]
@vvavdiya Hope it serves you well.

P.S. stars are welcome :)
