### ISSUE TITLE
Popup not getting positioned correctly when first opened

### ISSUE THREAD

**Issue by damo1884** [MrFrankel/ngx-popper#34]
Fix is here: https://github.com/MrFrankel/ngx-popper/pull/33

**Comment by MrFrankel** [comment]
@damo1884 can you provide a way to reproduce this?

**Comment by ktriek** [comment]
@MrFrankel in this [demo]( https://stackblitz.com/edit/angular-s2wdmv?file=src/app/app.component.html) you can see the popup is not correctly positioned.
 
![image](https://user-images.githubusercontent.com/4461059/40073253-56ff18b0-5844-11e8-9568-2fc87c521ec2.png)


Notice that if you scroll the page horizontally the popup gets fixed.
![image](https://user-images.githubusercontent.com/4461059/40073277-678b2c6e-5844-11e8-864b-41f1fcac6ccf.png)

**Comment by MrFrankel** [comment]
@ktriek thanks for the demo, seems its related to using float.

Ill look into it, thanks

**Comment by MrFrankel** [comment]
@ktriek sorry this is taken so long, iv'e been away on vacation.

It seems like an issue with popper.js itself, not sure why its miscalculating.
Ill try to investigate further but for now you can either use popperPositionFixed or set 
[popperModifiers]="{boundariesElement : 'viewport'}"

**Comment by ktriek** [comment]
@MrFrankel thanks, this workaround(adding `popperPositionFixed `or set` [popperModifiers]="{boundariesElement : 'viewport'}"`) fixed my problem.
