### ISSUE TITLE
Blur Content 

### ISSUE THREAD

**Issue by agustinbcu01** [MrFrankel/ngx-popper#35]
For Chrome, Opera and Safari.
The content looks blur. 
looks like is because the  transform: translate3d(...)

![image](https://user-images.githubusercontent.com/24256131/37167763-799d1e0a-22c8-11e8-8b3c-cea1f170451d.png)

**Comment by MrFrankel** [comment]
@agustinbcu01 I dont think its related to the library, its used quit extensively by me and others and I have not encountered this.
If you can provide a way to reproduce Ill gladly try to fix it.

Or you can disable the use of tranform3d for positioning by adding
 [modifiers]="{computeStyle: {gpuAcceleration: false}}"

if this helps let me know, so I can add it as a global property.

**Comment by agustinbcu01** [comment]
Works Great. Thanks.

**Comment by MrFrankel** [comment]
@agustinbcu01 can we close this then?

**Comment by agustinbcu01** [comment]
go ahead. thanks

**Comment by MrFrankel** [comment]
Thanks.

P.S stars are welcome :)
