### ISSUE TITLE
Issues when using Lazy load

### ISSUE THREAD

**Issue by ZeroCR** [MrFrankel/ngx-popper#4]
I am trying to implement Lazy load in my project and I am getting this error:

"Error: BrowserModule has already been loaded. "

And it is because this library is importing "BrowserModule"

Using Lazy load the recommendation is to import that library only in the app.component.

**Comment by MrFrankel** [comment]
Fixed in 1.0.1, thanks for bringing this up!

And if you could punch in a star for the repo that would be great 👍
