### ISSUE TITLE
Option to not display tooltip when text is empty

### ISSUE THREAD

**Issue by hspier** [MrFrankel/ngx-popper#40]
If the text to display is empty (or null), the tooltip displays a very small box with the arrow. It would be nice if there was a way to not display the tooltip when text content is empty.

As a workaround, using the popper-content, I can attach a class that will simply put 'display: none' when text is empty, but this needs to be repeated each time a tooltip has empty text.

Considering the tooltip can display HTML, simply checking for textContent could suffice to determine if there are text to display or not.

**Comment by MrFrankel** [comment]
@hspier why dont you use popperDisabled? 

`<div [popper]="someTextRef" [popperDisabled]="!someTextRef"></div>`

**Comment by hspier** [comment]
@MrFrankel I must have missed that flag, thanks for pointing it out!
