### ISSUE TITLE
Popper directive "content" input errors

### ISSUE THREAD

**Issue by hspier** [MrFrankel/ngx-popper#41]
The popper directive uses the content field in two ways:
- The name of a template reference
- A text string to display as a tooltip

In some situations, errors are thrown in the directive because of this dual use of field. 

Given this template:
```
<div [popper]="myProperty" (click)="onClick()"></div>
```
and this code:
```
public myProperty: string = 'Hello';
public onClick(): void {
    this.myProperty = 'World';
}
```
results in the following error:
```
TypeError: Cannot create property 'referenceObject' on string 'World'
    at PopperController.show (webpack-internal:///../../../../ngx-popper/ngx-popper.es5.js:2509:39)
    at eval (webpack-internal:///../../../../ngx-popper/ngx-popper.es5.js:2547:19)
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:421:31)
    at Object.onInvokeTask (webpack-internal:///../../../core/esm5/core.js:4944:33)
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:420:36)
    at Zone.runTask (webpack-internal:///../../../../zone.js/dist/zone.js:188:47)
    at ZoneTask.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:495:34)
    at ZoneTask.invoke (webpack-internal:///../../../../zone.js/dist/zone.js:484:48)
    at timer (webpack-internal:///../../../../zone.js/dist/zone.js:2065:29)
```
Also, looking at the code, there are no changes handler for the "content" input, only "popperDisabled".

**Comment by MrFrankel** [comment]
you should use it like so:
`<div [popper]="{{myProperty}}" (click)="onClick()"></div>`

**Comment by hspier** [comment]
This doesn't work as interpolation cannot be used with the form []. Angular error is:
```
Parser Error: Got interpolation ({{}}) where expression was expected...
```
Also using the form:
```
<div popper="{{myProperty}} ...></div>
```
results in the same error (Cannot create property 'referenceObject'...).

**Comment by MrFrankel** [comment]
`<div popper="{{myProperty}}" ...></div>`

this works fine for me, can use provide a more info?

**Comment by hspier** [comment]
myProperty needs to change after being initialized to another value. In the example above, I was using a click handler to change the value. The issue happens when I mouse over the element that should display the tooltip. Before invoking the click handler, the tooltip was displaying correctly.

**Comment by MrFrankel** [comment]
indeed this is a limitation, you should then use:
<div [popper]=popper1 ...></div>
`<popper-content #popper1>{{myProperty}}</popper-content>`

Ill think about a way of supporting you use case tomorrow.

**Comment by MrFrankel** [comment]
@hspier Ive just released a new version 2.2.1 with support for this.
<div popper="{{myProperty}}" ...></div>
should work fine now, can you please verify?

**Comment by hspier** [comment]
Just tested, the issue is resolved. Thanks for the quick fix!

**Comment by MrFrankel** [comment]
Sure, hope it serves you well.

PS stars are appreciated :)

**Comment by MrFrankel** [comment]
Sure, hope it serves you well.

PS stars are appreciated :)
