### ISSUE TITLE
Bad ref element

### ISSUE THREAD

**Issue by agustinbcu01** [MrFrankel/ngx-popper#43]
When a tag <a> is a floating right and is the last visible element, the popper points outside the tag, at the right side.

**Comment by MrFrankel** [comment]
Not quite sure what you mean, can you provide a way to reproduce it?

**Comment by agustinbcu01** [comment]
Let me work on a example with your sample. because I can't isolate my project issue. We use Bootstrap buttons. inside the popper content

**Comment by agustinbcu01** [comment]
Please close, I can't reproduce the situation in a clean environment. 
Thanks any way
