### ISSUE TITLE
popperForceDetection - no doc

### ISSUE THREAD

**Issue by vlio20** [MrFrankel/ngx-popper#45]
Could you please explain and add description to this configuration: 
popperForceDetection

**Comment by MrFrankel** [comment]
It was put in place to solve #25,
I cases where a onPush strategy is used in a parent component, this enforces a change detection event to be used when popper changes.

I will leave this open until I add description column to each property.

**Comment by MrFrankel** [comment]
added docs, let me know if I can close this
