### ISSUE TITLE
[Suggestion] remove the styling encapsulation 

### ISSUE THREAD

**Issue by vlio20** [MrFrankel/ngx-popper#47]
Hi,  
I don't see any benefit to adding the styling encapsulation. It just makes us (the users of the component) generate global stylings instead of putting the styles next to component.

You already have the encapsulation with the `ng__ prefix`. 

I don't mind PR if you agree.

**Comment by MrFrankel** [comment]
hmmm, id have to think about this...

**Comment by MrFrankel** [comment]
@vlio20 thinking about this, it will only be relevant if both the popper-content will have no ViewEncapsulation set and also its containing component.

If the containing parent has style encapsulation set then it will not propagate to and nested components anyway

**Comment by vlio20** [comment]
Yes, but in most cases, we use it as a child of the container - putting it all in a global file messes the scaffolding.
Anyway, I still don't see any reason for you to choose working with view encapsulation.

**Comment by MrFrankel** [comment]
It wasn't a consensus decision, that the Angular default, I agree it has no real benefit, i'm just worried about backward compatibility.

**Comment by vlio20** [comment]
You can release under major change version. Also, I think that the risk minimal.

**Comment by MrFrankel** [comment]
I've removed it in v2.4.0

**Comment by vlio20** [comment]
Awesome!
