### ISSUE TITLE
Can we display rich content in tooltip? like rendering HTML for custom tooltips.

### ISSUE THREAD

**Issue by yanbai-kooboo** [MrFrankel/ngx-popper#48]
What is the expected behavior?

Hi, I wonder that if we could render HTML in tooltip?
 It seems we can't do that now.
![image](https://user-images.githubusercontent.com/13013712/38024275-1afd820a-32b7-11e8-890d-385d7ffd7750.png)
Like in screenshot, "keyword.popper1Content" is a string of HTML fragment.

but now it just render HTML tag without any layout.

**Comment by MrFrankel** [comment]
@yanbai-kooboo you can simply do:
`<div popper="{{keyword.popper1Content}}"></div>`

or

```
<div [popper]="popper1Content"></div>          
<popper-content #popper1Content>{{keyword.popper1Content}}</popper-content>
```

**Comment by yanbai-kooboo** [comment]
@MrFrankel Thanks it works!!

**Comment by MrFrankel** [comment]
@yanbai-kooboo sure!

P.S, start are welcome!
