### ISSUE TITLE
Conditionally trigger poper

### ISSUE THREAD

**Issue by ronak-raithatha** [MrFrankel/ngx-popper#51]
Hey, 

Thank you for building this wrapper, it's proven pretty useful for me so far. Recently though, I've had a need to conditionally show the pop up, i.e. when the contents on the page have loaded AND the side nav is open. I wondering what the best possible way to get achieve this is. I've messed around with `popperTrigger` but that only takes a couple different options, not a custom event.

Thanks!

**Comment by MrFrankel** [comment]
@ronak-raithatha happy to hear you are finding this useful.

you can also open the popper programmatically using @ViewChild

`@ViewChild('popperContent1') 
   popperContent: PopperContent;

  onShow(){
   this.popperContent.show();
 }

onHide(){
this.popperContent.hide();
}
`

**Comment by MrFrankel** [comment]
closed due to lack of response

**Comment by leonardofmed** [comment]
Just to complement this question and answer, how can I use this method you provided but for more than one tooltip? Like popperContent1 and popperContent2 for example.

**Comment by k-i-k-s** [comment]
@leonardofmed you can use @**ViewChildren** and **QueryList**
