### ISSUE TITLE
Dynamically register event listeners

### ISSUE THREAD

**Issue by hspier** [MrFrankel/ngx-popper#52]
Popper directive automatically registers for events using HostListener which always register all events no matter the trigger to open the Popper. The code then simply return in the event handler method when the event doesn't match the showTrigger.

As an enhancement, it should use the Renderer2 to listen only to the events that are defined as showTrigger. Automatically registering them has the effect of adding them in the EventManager which adds more logic around the actual event for no purpose as they are cancelled out in the directive.

**Comment by MrFrankel** [comment]
@hspier This is a very valid point, like most application, there was never the intent for so many Listeners when writing this tool started, So I opted for better readability over performance.

It is defiantly on my to do list however its a substantial change and I hope to get to it soon.

**Comment by MrFrankel** [comment]
@hspier ive created a branch called dynamic-events-handlers with an implementation of this, its also releases in a pre release 2.8.0-next.

Id like to hear your thoughts before I release it.

**Comment by MrFrankel** [comment]
released in 3.0.0
