### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by fhurta** [MrFrankel/ngx-popper#53]
This is rather discussion topic.
Couldn't the background color be a property (e.g. `[popperBackground]`)?

I used your component and spent some time looking for a problem as the background of the tooltip was transparent. After some time I realized it is by default and started figuring out how to change it. As I cannot change the  encapsulation in my component, I ended up setting 

	::ng-deep {
	 .ngxp__container{ 
		background: #ffb0b0;
	  }
	}

in the component's style (but `ng-deep` is deprecated so I would prefer some better solution).

I like the component but setting the background seems to me a bit complicated (perhaps not well documented) for the scenario everyone needs to solve (can't imagine many cases the transparent background would fit).

**Comment by MrFrankel** [comment]
@tonysamperi @fhurta I am considering adding an input like popperStyles which will be an object you can pass css properties to.
`[popperStyles]="{backgroundColor: 'black'"}`.

Would that fit your needs?

**Comment by tonysamperi** [comment]
@MrFrankel Indeed. 
Cool solution. It should cover everything.
Although, wouldn't be better to have some "forRoot" method to set default style for every popover?
The popperStyles may be usefull nonetheless to override defaults.

Anyway I could do for you the "popperStyles" part and prepare a pull-request if you need a hand.

All the best and thank you

**Comment by MrFrankel** [comment]
@tonysamperi well, the best use case is to use classes, but Angular encapsulation makes that a but complicated at times.

the popperStyles would also be a forRoot property which you could apply for all and then override it if needed.

Thanks for the offer on the PR but iv'e already implemented it.
Ill release it soon after a few tests.

**Comment by MrFrankel** [comment]
@tonysamperi try 2.8.0 let me know how it works.

note this popperStyles is aligned with ngStyles so you should use it as such:
`[popperStyles]="{'background-color: 'blue''}"`

**Comment by tonysamperi** [comment]
about to try in a sec. 

Thanx

**Comment by tonysamperi** [comment]
Works, but the arrow remains grey :)

**Comment by MrFrankel** [comment]
@tonysamperi alas!.
missed that, Ill get that too.

Thanks!

**Comment by tonysamperi** [comment]
> well, the best use case is to use classes

Yeah absolutely. I haven't had my coffee yet.
Actually for defaults some rules in styles.css (or in my case scss) do the job!

> missed that, Ill get that too.
ahahah don't worry

**Comment by MrFrankel** [comment]
@tonysamperi so the arrow background is a bit more complicated as it is a triangle and its background is derived through its border-color.

I have to go out for a few hours, ill get a solution later today.

**Comment by MrFrankel** [comment]
never mind, got it.

Try 2.8.1

**Comment by tonysamperi** [comment]
@MrFrankel 
perfect. It works.

**Comment by tonysamperi** [comment]
Actually if you use "backgroundColor" instead of "background-color" the arrow remains grey.
I know. I'm a pain in the ass. :D

**Comment by MrFrankel** [comment]
does backgroundColor work with the popper-content itself?

**Comment by tonysamperi** [comment]
yep. The popper is red and no errors in console.

**Comment by MrFrankel** [comment]
ok, thats an easy fix. ill get that up later today.

Thanks for all the help!

**Comment by tonysamperi** [comment]
Yeah, I saw this is the line...

`this.popperOptions.styles && this.popperOptions.styles.hasOwnProperty('background-color') `

thanks again for your work.

All the best

Tony

**Comment by MrFrankel** [comment]
@tonysamperi release 2.8.2, supporting backgroundColor too.

**Comment by tonysamperi** [comment]
@MrFrankel Testing... :)

**Comment by tonysamperi** [comment]
@MrFrankel Alright. Everything seems ok!
https://stackblitz.com/edit/mat-card-multiple-sections

Great job!
