### ISSUE TITLE
Cannot set property 'referenceObject' of undefined

### ISSUE THREAD

**Issue by hspier** [MrFrankel/ngx-popper#54]
For the popper directive, when the 'content' property is undefined, the following error is thrown:

`
TypeError: Cannot set property 'referenceObject' of undefined
	    at PopperController.ngOnInit (webpack:///./node_modules/ngx-popper/ngx-popper.es5.js?:2490:35)
	    at checkAndUpdateDirectiveInline (webpack:///./node_modules/@angular/core/esm5/core.js?:12585:19)
`

This is because the code assumes that if 'content' is not a string, it is a PopperContent but fails to make sure that it is a proper object. The use case for this is when content will be a string but is initially not set to a value and is therefore undefined.

Workaround is to force 'content' to an empty string instead of leaving it as undefined.

**Comment by MrFrankel** [comment]
@hspier I am not sure about this one, my main concern is this might hide bugs in the user's code, I'm also not keen in implicitly assuming undefined will eventually be a string.

What if a catch this error and throw a more explicit error? that way the user will set the initial value?

What do you think?

**Comment by hspier** [comment]
I think that what is instantiating the popper content (or grabbing it) should be delayed in ngOnChanges for a change on "content". Doing it in ngOnInit is prone to this type of error due to inputs not necessarily in the state they should be. 

Basically don't do anything in ngOnChanges until content is defined and when it is defined then do the instantiation logic. This would also support the case when content changes and the directive needs to reinstantiate the popper.

**Comment by MrFrankel** [comment]
@hspier I think there is something conceptually wrong with waiting for the data to be valid in the onChanges before initiating the component, I see all kinds of issues arising from this.
Also, it goes against the life cycle of Angular component, they define the ngOnInit as the point where all inputs are already set.


The two options that might be relevant for me would be.

1. Apply an empty string as a default to content, seems easiest and least prone to issues, through i'm not crazy about it.
2. Only In case content is undefined, defer the initilization to the first time it is defined in the changes, This seems a more "correct" way, but much more complex and prone to issues.

**Comment by hspier** [comment]
ngOnInit is where inputs are set, but only the first value for inputs. ngOnInit is never called more than once as opposed to ngOnChanges which can be called more than once. Also, it is not against the lifecycle of Angular to refresh the component when an ngOnChanges is triggered: it is the precise place to do it. From the doc:

> Respond when Angular (re)sets data-bound input properties. [...] Called before ngOnInit() and whenever one or more data-bound input properties change.

In general, a component/directive can do one time initialization in ngOnInit for data that is not expected to change OR to bootstrap the component/directive. For any property that can change ('content' falls in that category), there should be code that supports this in ngOnChanges. In the documentation it is stated that ngOnInit is called AFTER the first ngOnChanges so you could only deal with ngOnChanges for 'content' without breaking anything.

**Comment by MrFrankel** [comment]
Currently the directive responds to changes in content on ngOnChanges, and the bootstrapping is done in the ngOnInit, so this seems aligned with the Angular way.

So I would think this is in sync with number 2.
In cases where content is undefined, we will defer the bootstrapping to the when content becomes defined.

**Comment by ArtemGrachov** [comment]
> 1. Apply an empty string as a default to content, seems easiest and least prone to issues, through i'm not crazy about it.

It helped me, thanks.
