### ISSUE TITLE
Incorrect Popper Placement Options?

### ISSUE THREAD

**Issue by nileshbhagwat** [MrFrankel/ngx-popper#56]
@MrFrankel 

What is use of popperPlacement options that starts with 'auto-'? 
'auto-top' | 'auto-bottom' | 'auto-left' | 'auto-right' 

These are not valid options as per https://popper.js.org/popper-documentation.html

Also auto-start, auto-end, these options are missing from ngx-popper doc

**Comment by MrFrankel** [comment]
@nileshbhagwat its just a documentation issue, all placements are passed directly to popper constructor.

I've fixed the docs now, can this be closed?

**Comment by nileshbhagwat** [comment]
@MrFrankel Yes it was documentation issue, thanks for confirming the same.

Closing issue based on https://github.com/MrFrankel/ngx-popper/commit/1ab5c4255e7b68c0449ec3e35a2425245ffc803e

**Comment by MrFrankel** [comment]
@nileshbhagwat thanks for bringing this up!
