### ISSUE TITLE
Slower performance when using multiple poppers (i.e. ngFor)

### ISSUE THREAD

**Issue by clarencecastillo** [MrFrankel/ngx-popper#58]
Hey @MrFrankel, thank you so much for this wrapper!

My use case involves nesting a popper inside an infinite-scrolling component via *ngFor. To illustrate, I'm trying to use this library to implement something like a context-menu button for every item in the list.

From what I noticed, performance significantly gets degraded as more items are loaded. Takes a longer time for my popper to show/hide and as it waits, the browser freezes up. Profiling via chrome dev tools seems to point out that it's the event handling that's taking a very long time to finish. 

<img width="1919" alt="screen shot 2018-05-24 at 11 40 23 am" src="https://user-images.githubusercontent.com/5035728/40463609-c488e3ec-5f48-11e8-870a-6d14a41e6c4e.png">

The first chunk maps to when I first clicked the reference object to show the popper. The second chunk maps to when I clicked outside the reference object to hide the popper. 

Am I doing something wrong? Appreciate any help regarding the above. Thanks!

**Comment by MrFrankel** [comment]
@clarencecastillo first, popper are angular components, as such they require resources and having many on the page will effect performance.
I am working on some improvements to the event handling mechanism which will improve the performance, but it would still be better practice if you are using infinite scroll to destroy element's that are not in view.

This can be achieved by simply wrapping each element with *ngIf.

**Comment by MrFrankel** [comment]
@clarencecastillo Ive release a prerelease version 2.8.0-next, it has some performance improvements.

cant you see if it works better?

**Comment by clarencecastillo** [comment]
@MrFrankel Thanks for the follow up! The pre-release version 2.8.0-next significantly reduced the time to show/hide the popper from 10s to just 2s @ 100+ popper components loaded.

In case somebody else encounters the same problem, I've followed the suggestion to destroy element's that are not in view by moving my popper-content component outside my *ngFor and wrapped my popper reference element with an *ngIf which renders the element only when the user hovers over the component. My popper-content is still able to access the data in my *ngFor using the list index.
