### ISSUE TITLE
Need to overlap reference element

### ISSUE THREAD

**Issue by clarencecastillo** [MrFrankel/ngx-popper#59]
Hey again @MrFrankel, thanks again for this component!

Just wanna ask if there's a way to specify the offset relative to the reference element? I've tried setting the offset modifier but I think it's not meant to be used that way (see snippet below). I'm trying to use this component to implement a nest-able context menu and to achieve that, I'd need to overlap the parent popper with the child popper so as to keep it open on hover.

```js
this.popperModifiers = {
  offset: {
    offset: '-10px',
  },
};
```
I tried hardcoding a negative margin from the stylesheet but that wouldn't work if the nested component flips over to the other side.

<img width="577" alt="screen shot 2018-06-06 at 3 11 40 pm" src="https://user-images.githubusercontent.com/5035728/41023046-dfb29d66-699d-11e8-8ce1-fffab00cf8f9.png">

**Comment by MrFrankel** [comment]
@clarencecastillo Happy to hear this serves you well.

To overlap the reference element you can simply set the offset and disable the flip functionality.
`[popperModifiers]="{offset: {offset: '0,-10px'}, flip: {enabled: false}}"`

Let me know if this helps

**Comment by clarencecastillo** [comment]
Is there a way to do it while keeping the flip modifier enabled? Due to some other UX consideration, I am unable to statically fix my Popper's position. It could potentially go out of the viewport so I would still need the flip modifier to keep it in view.

**Comment by clarencecastillo** [comment]
<img width="424" alt="screen shot 2018-06-06 at 11 15 39 pm" src="https://user-images.githubusercontent.com/5035728/41047716-c26b9ca2-69df-11e8-8d2b-fa40e23f5bae.png">

Setting the offset to `0,-10px` and disabling flipping does the trick but opening one by the edge of the viewport results in the popper covering the parent popper.

<img width="386" alt="screen shot 2018-06-06 at 11 03 51 pm" src="https://user-images.githubusercontent.com/5035728/41047119-67bca0cc-69de-11e8-953c-d6dbef8c7c0d.png">

Ideally, it should behave similarly to the first screenshot above, but on the other side of the first popper.

**Comment by clarencecastillo** [comment]
After taking a look at popper.js's documentation, it seems that there's no way to get this to work without dynamically setting the offset value using the `fn` modifier property. Instead of taking that route, I decided to set the modifier to `[popperModifiers]="{offset: {offset: '0,-10px'}, flip: {enabled: false}}"` as suggested, and manually flip the popper according to the reference element's position relative to its parent:

```js
adjustPopperPosition(popper: PopperController) {
    const ref: HTMLElement = popper.getRefElement();
    const container: HTMLElement = ref.parentElement;
    if (ref.offsetLeft + ref.offsetWidth === container.offsetWidth) {
      this.contextMenuPositon = 'left';
    } else {
      this.contextMenuPositon = 'right';
    }
  }
```
`[popperPlacement]="contextMenuPositon"`

I admit that it's a bit smelly but it does the job lol. Really appreciate the help!
