### ISSUE TITLE
Popup sometimes closes when clicking inside

### ISSUE THREAD

**Issue by wlievens** [MrFrankel/ngx-popper#60]
The popup sometimes closes when clicking inside, but only in Chrome. Tis occurs when `isMouseOver` is set to `false` by a spurious `mouseleave` event. Apparently Chrome has an issue where it triggers `mouseleave` events if you have clicks in quick succession.

More info: https://stackoverflow.com/questions/45266854/mouseleave-triggered-by-click

Are there any workarounds available for ngx-popper? I'm experiencing this problem very often.

**Comment by wlievens** [comment]
More evidence of this bug
https://stackoverflow.com/questions/47649442/click-event-affects-mouseenter-and-mouseleave-on-chrome-is-it-a-bug

**Comment by wlievens** [comment]
There appears to be a proper defect report with Chromium - https://bugs.chromium.org/p/chromium/issues/detail?id=798535

**Comment by MrFrankel** [comment]
Thanks for bringing this up, and all the research. I’m away for a couple of days but I’ll look into it as soon as I get back. Have you tried setting popperHideOnMouseLeave to false?

**Comment by wlievens** [comment]
Hi, thanks for replying so quickly. I have tried `popperHideOnMouseLeave` but it has no effect on the issue. I read through the Chromium bug report, it seems to be pretty challenging to reproduce for them, which is weird because for me it happens for about 20% of all clicks. I haven't made a minimal reproducable example yet.

**Comment by MrFrankel** [comment]
You can also control the popper programmatically by calling the show hide methods yourself and manage the logic that way, at least for now anyway
