### ISSUE TITLE
Add an abbility to display html instead of text

### ISSUE THREAD

**Issue by fedotxxl** [MrFrankel/ngx-popper#62]
I can use #tooltipcontent to do it but I need really simple html (like `hello <strong>world</strong>`) and current solution makes things too complicated

**Comment by MrFrankel** [comment]
@fedotxxl My main intention was to use popper-content for HTML, but I guess there would be cases where that adds some overhead.

Let me check all ramification of this as it might be a breaking change.

**Comment by MrFrankel** [comment]
@fedotxxl Ive released an npm version 4.0.0-next, it should except now html.
Can you verify this and ill release it.

**Comment by fedotxxl** [comment]
Checked 4.0.1 - it works
