### ISSUE TITLE
Import from 'ngx-popper' not working

### ISSUE THREAD

**Issue by Tucaen** [MrFrankel/ngx-popper#63]
After updating from version 2.7.1 to 3.0.1 the import (import {NgxPopperModule} from 'ngx-popper';) is no longer working.
Error Message: Module '".../node_modules/ngx-popper/ngx-popper"' has no exported member 'NgxPopperModule'.

Is there something else to change, that I missed?

**Comment by Tucaen** [comment]
Well it seems something went wrong on during the install. After deleting the complete node_modules folder and reinstalling, it's working again.
Sorry!

**Comment by MrFrankel** [comment]
@Tucaen no problem! hope it serves you well :)
