### ISSUE TITLE
GlobalEventListeners aren't cleared

### ISSUE THREAD

**Issue by Tucaen** [MrFrankel/ngx-popper#64]
Looks like there's a typo, in the clearGlobalEventListeners function, to me:
```
private clearGlobalEventListeners() {
    this.globalEventListeners.forEach(evt => {
      evt && typeof evt === 'function' && evt();
    });
    this.eventListeners.length = 0; //should be this.globalEventListeners
  }
```

**Comment by MrFrankel** [comment]
@Tucaen should be fixed in 4.0.1

**Comment by Tucaen** [comment]
No problem :)
It has the effect, that the array get's larger and larger every time the popover is oppend.

**Comment by MrFrankel** [comment]
True, well, should be fixed now anyway, good catch!

**Comment by Tucaen** [comment]
I'm currently struggeling a bit to install version 4.0.1
![image](https://user-images.githubusercontent.com/12460448/41852347-1704d3be-788b-11e8-9786-07da432c1db0.png)

Already tried deleting the whole node_modules folder and install from scratch twice this time.

I guess I'll finde the problem a few minutes after posting this :smirk:

**Comment by MrFrankel** [comment]
popper.js is now a peer dependency, try installing popper.js too

**Comment by Tucaen** [comment]
Works fine 👍 
Next time I will do both, deleting node_modules and read the changes 😇
