### ISSUE TITLE
Placement not consistent

### ISSUE THREAD

**Issue by jamra** [MrFrankel/ngx-popper#67]
Thanks for the component. It's really nice to work with.

I'm trying to get the actual popover placement when I pass in 'auto' so I'm running 

```javascript  
const pop_container = (<HTMLElement>this.popper.content['popperInstance'].popper);
const popPlacement = pop_container.getAttribute('x-placement');
```

It's working most of the time, but there is a very wide popover on a very wide reference element and it keeps stating 'bottom' instead of 'right'. I'm doing a lot of sizing calculations, adding in scroll bars and max widths. 

I was wondering if there is a better way to do this or if you can give me access to the onUpdate method so I can run my calculations there instead of on "onShown"

**Comment by MrFrankel** [comment]
@jamra I can look into suppling a hook for the onUpdate, but im not sure what the issue it.

The popper states position 'bottom' in the x-placment attribute event though it's actual position is not?

**Comment by jamra** [comment]
That is correct and it happens infrequently but on some elements consistently. 

I wanted to try and hook into onUpdate for my calc height function because my calc height function depends on knowing the correct x-position. 

So just to clarify when I inspect element, the x-position is correct but inside the onShown event, it is set to bottom when it’s really right.

**Comment by jamra** [comment]
Maybe I can solve this with a custom modifier. I'll try that out first. Please hold on this. I don't want you to do work for no reason.

**Comment by MrFrankel** [comment]
Sorry I hadn’t had time to look into this, I think this issue should be addressed anyway. I’ll try get a version out tomorrow

**Comment by MrFrankel** [comment]
@jamra OK, it was easier then I thought.
As of v 4.1.0 you can now add a popperOnUpdate output to the directive and get the popper data.instance as an argument.
There you should have the popperPlacement which should map to the actual placement

**Comment by jamra** [comment]
Thank you! 
I ended up using the computeStyle modifier and it worked. I should just use an unused modifier that is before computeStyle. I couldn't find documentation on how to make custom modifiers. The link on popperjs's documentation goes to a 404. 

Just got it working. I'll check out your way a bit later, but I'm loving this library!

**Comment by nicolasmatias** [comment]
Hello jamra,

i thin i have the same problem as you when i use ngfor in some page.


`<div>
  <div
    [popper]="popperContent"
    [popperPlacement]="placement"
    (popperOnUpdate)="test($event)"
    (popperOnShown)="showTooltip()"
    (popperOnHidden)="closeTooltip()"
    [popperDisabled]="disabled"
  >
    <ng-content></ng-content>
  </div>
  <div #popperContentPanel [ngClass]="placement == 'bottom' ? 'popperContentPanelBottom' : 'popperContentPanel'">
    <popper-content #popperContent><p>{{tooltipText}}</p></popper-content>
  </div>
</div>` 

this is my tooltipComponent, but i dont know why, the Popper instances have 'top' placement exept the first item in my ngfor.


i implement the tooltip like that in my post.component :

`  <tooltip style="margin-right: 18px;" [tooltipText]="'media-viewer.sort' | translate" [placement]="'bottom'">
      <div class="icon">
        <div style="width: 18px; height: 16px;">
          <svg-icon style="width: 18px; height: 16px;" src="../../assets/svg/filterMedia.svg"></svg-icon>
        </div>
      </div>
    </tooltip>`


do you have any details on how you solved this problem?
