### ISSUE TITLE
Popper not showing on disabled button

### ISSUE THREAD

**Issue by alekplay** [MrFrankel/ngx-popper#68]
Not sure if this is a bug or not, but I'm not able to get the popper to appear when hovering over a `disabed` button. Removing the `disabled` attribute makes the popper appear as expected.

If this is intended behavior, what is the recommended solution for when you'd like to disable a submit button when a form is invalid, but show a tooltip to inform the user why it's invalid?

**Comment by MrFrankel** [comment]
@alekplay a disabled button does not fire mouse events therefore it cannot show on hover.
I would suggest adding a class called disabled and applying styles on it.

Or you could wrap the button in another element and have the popper on it.

**Comment by alekplay** [comment]
Great, thank you for the explanation!
