### ISSUE TITLE
popperHideOnScroll with hidden button

### ISSUE THREAD

**Issue by RwbyChan** [MrFrankel/ngx-popper#69]
I have a button that appears on hover of a specific element that has the popper inside of it, the button will open the popper. I also have popperHideOnScroll set to false.

When I click on the button, the popper opens, when I scroll with keeping my mouse on the div that has the button to open the popper, it works,  but when I scroll when not having my mouse on that div (so the button that opens the popper isn't visible) the popper hides when scrolling...

Could this be solved?

**Comment by MrFrankel** [comment]
@RwbyChan Im not sure I understand the use case, could you create a demo in stackblitz or somewhere?
