### ISSUE TITLE
Default trigger hover kinda breaks example app

### ISSUE THREAD

**Issue by ryanhyslop** [MrFrankel/ngx-popper#7]
I noticed in doing my PR that the default trigger being set as hover:
https://github.com/MrFrankel/ngx-popper/blob/d73d6ab3b9957a34598f3b8dee8dc033b63820d7/src/popper-content.ts#L144

creates some unusual behaviour in the example app when `popperShowOnStart` is true.

In particular the boundary examples which aren't expected to disappear now disappear when you hover over them. In the demo link (https://mrfrankel.github.io/ngx-popper/) the trigger is actually `undefined` meaning it never hides on mouseout.

 ![demo](https://user-images.githubusercontent.com/323687/29571011-03dbf772-8750-11e7-96ff-2a9e7ffd5248.png)

Just wanting to canvas opinion here as I had thought I'd broken something when checking, wonder whether a trigger type of `NONE` is appropriate for those that do not want the popover to ever hide?

**Comment by MrFrankel** [comment]
@ryanhyslop A trigger type of None is a good option to have, I can add it tomorrow unless you want to take a crack at it.

I like it!

**Comment by MrFrankel** [comment]
@ryanhyslop did you get around to tackling this?

**Comment by MrFrankel** [comment]
Added none trigger type in version 1.1.0.
