### ISSUE TITLE
When using click trigger on touch devices, the popup is hidden immediately after it's shown

### ISSUE THREAD

**Issue by Necroskillz** [MrFrankel/ngx-popper#70]
See repro here: https://ngx-popper-touch-issue.stackblitz.io/ (run on a mobile device or chrome emulator).

The popper is shown, but hidden immediately when using click trigger (there are some spots where it stays open when you click on them, but most of the time it closes right away. And even if it stays open, the same issue will prevent it from closing).

This issue didn't happen in 2.8.1 and earlier. I traced it to the way the event handlers are registered. The problem is that on devices both `touchstart` and `click` handlers are triggered, so it opens on `touchstart`, then `click` triggers, and hides it (and also now counts as click on outside because `touchstart` started listening for this.

I added some debug info to ngx-popper code (this happens after clicking once):

![image](https://user-images.githubusercontent.com/346477/43410274-a280583a-9426-11e8-9595-97b1a425e9fa.png)

**Comment by MrFrankel** [comment]
@Necroskillz hey, checking...

**Comment by MrFrankel** [comment]
Indeed it seems it’s a bug, I’ll push a fixed version by tomorrow I hope, I’ll thanks for bringing it up

**Comment by MrFrankel** [comment]
@Necroskillz Ive released version 4.2.0, can you verify this fixes the issue?

**Comment by Necroskillz** [comment]
Yeah, I made pretty much same fix and put it to our local npm server, so it should be fine. Thx for the quick fix.

**Comment by MrFrankel** [comment]
Thanks for helping wth this!
