### ISSUE TITLE
Clickoutside doesn't work on touch devices

### ISSUE THREAD

**Issue by Dosant** [MrFrankel/ngx-popper#73]
Hi,
I am using 4.2.0 version. 

For a popper trigger I am using 'click'. 
Clickoutside behaviour works as expected on desktop, but for mobile, touching outside of the popover doesn't trigger the popup close.

**Comment by MrFrankel** [comment]
@Dosant This works on fine on Iphone, what device can you see this not working?

**Comment by Dosant** [comment]
@MrFrankel, Also iPhone. I will try to reproduce in sandbox.

**Comment by Dosant** [comment]
@MrFrankel, please try: https://angular-e4bhjr.stackblitz.io 

For me the popover doesn't close itself when I touch outside. 
I am using an iPhone.

**Comment by MrFrankel** [comment]
@Dosant Thanks for the repro but I can t get it to work, I dont see any popup at all

**Comment by Dosant** [comment]
HI @MrFrankel,

So I digged a bit deeper into the issue.
It looks like it is indeed doesn't properly work on iPhone.

I found out, that when touch is happening on non "clickable" element, iOS doesn't generates click event.[https://www.quirksmode.org/blog/archives/2010/09/click_event_del.html].

So this handler in such case, won't be fired: 
`this.renderer.listen('document', 'click', this.hideOnClickOutsideHandler.bind(this))`

In my app I've implemented the (workaround)[
http://gravitydept.com/blog/js-click-event-bubbling-on-ios] for this iOS behaviour. And the popover is closing as expected now. 

From ngx-popper side, I think the clickouside handling logic should also listen to touchend events on document.

**Comment by MrFrankel** [comment]
Hey @Dosant,
Thanks for researching this, sorry I havent had time to look into it, summer holidays etc...
I figured it was just adding a touchstart event listener, just need to see how it act's on other platforms.

I should have it fixed in the next couple of days.

**Comment by MrFrankel** [comment]
@Dosant  Sorry it toke so long, should be fixed in version 5.1.6, please confirm.

**Comment by Dosant** [comment]
@MrFrankel, great, works! Thanks.
