### ISSUE TITLE
hideOnClickOutside doesn't work if popperTrigger is 'none'

### ISSUE THREAD

**Issue by blakekl** [MrFrankel/ngx-popper#77]
Reproduction of this issue [here.](https://stackblitz.com/edit/angular-rhd2hm)

Not sure if this is a problem with ngx-popper or just PopperJS, but I would still expect the hideOnClickOutside to work.

**Comment by MrFrankel** [comment]
@blakekl When opening the popper programmatically as you are doing its your responsibility to manage opening and closing it.
I am closing this as it is a duplicate of #76.
