### ISSUE TITLE
Transparency issue

### ISSUE THREAD

**Issue by StephenAArredondo** [MrFrankel/ngx-popper#78]
I'm trying to implement a popper with a popper-content, but every attempt has resulted in the background being transparent. Not sure what's going on.

Here's the stackblitz reproducing this issue:
https://stackblitz.com/edit/angular-1t6dwb

**Comment by MrFrankel** [comment]
@StephenAArredondo add 

`popper-content .ngxp__container{
  background: green;
}`

to your styles.css

**Comment by StephenAArredondo** [comment]
It worked in the stackblitz, but not working in my application. I don't have any other styling on it other than the above, 

![sameproblem](https://user-images.githubusercontent.com/8017722/46037837-66343800-c0d7-11e8-9ee2-5c58e32b8155.png)

**Comment by MrFrankel** [comment]
If you are using Angular css encapsulation(which is enabled by default) then it will not apply to internal component's such as popper-content.

you can set a global css file, which is the common practice and add it to your index.html

**Comment by tonysamperi** [comment]
@StephenAArredondo you have your rule in your app.component so it wont apply.
You have 3 solutions:

1.  use the outer styles.css
2.  add `encapsulation: ViewEncapsulation.None` to your app component
3. use the `[popperStyles]` attribute and set styles for each component (you can use a service to avoid duplicate code)
