### ISSUE TITLE
Popper needs to break out of overlay hidden

### ISSUE THREAD

**Issue by ChristofFritz** [MrFrankel/ngx-popper#79]
Hi, 

i have a problem where I need some help. The element that needs a popover is inside a scrollable div that has "overflow-x: hidden; overflow-y: scroll;". 
The popver currently is being cut off because it overflows this container, but it needs to overflow it.
Can the popver somehow be placed in the parent component? Or is there an other way to deal with this problem?

Here is a Picture of the problem: You can see the popover being cut off
![grafik](https://user-images.githubusercontent.com/24923242/46202597-8c481b00-c317-11e8-84c4-dd09f7730fc8.png)

**Comment by ChristofFritz** [comment]
Ok, i found a solution:
`[popperModifiers]="{preventOverflow: {boundariesElement: 'viewport'}}" [popperAppendTo]="'body'"`

**Comment by MrFrankel** [comment]
@ChristofFritz, 
You can also use [popperPositionFixed]="true"
This should work in most cases
