### ISSUE TITLE
Popover won't close when clicking the trigger on touch devices

### ISSUE THREAD

**Issue by Dosant** [MrFrankel/ngx-popper#82]
Hi,
I am using latest 5.1.7 version and iPhone. 

On touch devices popover won't close when clicking the trigger. (I guess there is some conflict with handling touch/click events)

Here is the repo to reproduce: 
https://stackblitz.com/edit/ngx-popper-touch-bug

On touch device after opening the popover by clicking the button, clicking this button again won't close the popover.

**Comment by MrFrankel** [comment]
@Dosant checking...

**Comment by MrFrankel** [comment]
After investigating it seems this only happens on Safari ios.
It seems that clicking on the buttons also triggers the closeOnClickOutside so the popper gets reopened after closing.

Ill have to think about the solution a bit in order not to break anything. 

For now you can avoid this behaviour by using the popperHideOnClickOutside="false"

**Comment by cherlin** [comment]
We're seeing it on Android as well as on iOS devices, in both Safari and Chrome. Any updates on this issue?

**Comment by sonikasharma1403** [comment]
Hi @MrFrankel , This issue is still reproducible. Is there any update on this?
