### ISSUE TITLE
including ngx-popper in an angular 4 project with AOT

### ISSUE THREAD

**Issue by inquiztr** [MrFrankel/ngx-popper#84]
I am having a problem using ngx-popper in our angular 4 project. Everything works fine when we build our project in dev/JIT but when we compile with AOT we get an error in webpack : 

Error: Metadata version mismatch for module c:/Source/TSC.WebFactory/TSC.WebFactory.Web2/node_modules/ngx-popper/ngx-popper.d.ts, found version 4, expected 3

is there any way to get around this? for now we avoid the npm package and use the 4 source files (directive/model/module etc) directly.

**Comment by MrFrankel** [comment]
@inquiztr  I'll look into this but I cant gurentee that the latest version of ngx-popper will work with an outdated version and Angular.
