### ISSUE TITLE
hideOnClickOutside not working together with dialog

### ISSUE THREAD

**Issue by joelonilsson** [MrFrankel/ngx-popper#96]
### Current behavior:
When opening a dialog (MatDialog in my case) from the popper, any click will close the popper. No matter if it's inside the dialog or it's backdrop.
This is when having set hideOnClickOutside to true.

### Expected behavior:
The popper should not be hidden when clicking on a dialog opened from the popper, or when clicking the backdrop of the dialog.

### Possible solution:
The dialog is added inside div.cdk-overlay-container in the bottom of the body.
Adding something like `$event.srcElement === document.querySelector('.cdk-overlay-container') ||
      document.querySelector('.cdk-overlay-container').contains($event.srcElement)` to the if-statement in hideOnClickOutsideHandler should work.

**Comment by MrFrankel** [comment]
@joelonilsson sorry Iv'e missed this one, can you provide a reproducible example? on stackblitz preferable

**Comment by joelonilsson** [comment]
@MrFrankel No worries, we managed to get around it by re-binding the original hideOnClickOutsideHandler. But it would be appreciated if you could fix it anyways.
Here's a small demo of the issue: https://angular-ntaw42.stackblitz.io

**Comment by MrFrankel** [comment]
@joelonilssoncan you provide the like in order to edit the repo? so I can check how to resolve this?

**Comment by joelonilsson** [comment]
@MrFrankel I accidentally sent the link without the edit mode. I updated it now.

**Comment by joelonilsson** [comment]
@MrFrankel Only when there is a dialog or something with a backdrop active. 
So if only the popper is active, then clicking outside should close it. But if you open a dialog from the popper, then clicking anywhere (.cdk-overlay-container), should keep the popper open.

Maybe this is not preferred behavior by everyone, but in that case it could be configurable.

**Comment by joelonilsson** [comment]
@MrFrankel This is how I think it should behave. But this uses a workaround with re-binding the handler.
https://stackblitz.com/edit/angular-zodtnq

**Comment by MrFrankel** [comment]
@joelonilsson there is no way for a popper to know what should close the popper or not, popper listens  to a click on the body.
In your use case the dialog should stop click events from propagating, if the Dialog dosnt support it you can add it yourself when the dialog is open like so:
document.querySelector('.cdk-overlay-container').addEventListener('click', (event) => event.stopPropagation( 

just remember to clear the listener when the dialog is closed
